version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./source:/var/www
    depends_on:
      - mysql
      - redis

  # NGINX Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: quiz_sys
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: quiz_root
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Redis Service
  redis:
    image: redis:alpine 
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: